baseurl = "http://deliveringfood.appspot.com/public/"
languageCode = "en-us"
title = "Comida a casa"
theme = "comida"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Jose Angel Espinoza Portillo"
	description = "Yo soy @onlyangel"


	# Navigation
	[params.navigation]
		brand = "Comida a tu chamba"

		[params.navigation.links]
			about     = "Lo tenemos"
			services  = "Planes"
			portfolio = "Como funciona"
			contact   = "Contacto"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Come bien! Come sano!"
		subtitle   = "La mejor manera de lograr tus objetivos alimenticios semana a semana."
		buttonText = "Conose mas"


	# About section
	[params.about]
		headline    = "Tenemos lo que necesitas!"
		description = "Te resolvemos el problema de no encontrar comida saludable cerca de tu trabajo. Mandandote un menu diseñado por excelentes cheffs a tu oficina, con todo lo que necesitas para cumplir con tus objetivos alimenticios."
		buttonText  = "Conose los Menus!"


	# Service section
	[params.services]
		headline = "Los MENUs"

        [[params.services.list]]
            icon = "fa-heartbeat"
            title = "Baja de Peso"
            description = "Diseñado para que obtengas la menor cantidad de calorias con el mejor sabor."

        [[params.services.list]]
			icon = "fa-balance-scale"
			title = "Mantente Sano"
			description = "La mejor combinacion de sabores que te permitiran seguir en tu linea."

		[[params.services.list]]
            icon = "fa-user-plus"
            title = "Sube de peso"
            description = "Para ti que necesitas subir de peso tenemos este menu para que cumplas tu objetivo de manera sana."

        [[params.services.list]]
            icon = "fa-heart"
            title = "Puro Musculo"
            description = "Si jalar mas es tu objetivo. Este menu te ayudara a lograrlo."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
